export const FilterNameMap = new Map<string, string>([
  ['dateIs', 'es'],
  ['dateIsNot', 'no es'],
  ['dateBefore', 'antes'],
  ['dateAfter', 'despues'],
  ['startsWith', 'es'],
  ['contains', 'contiene'],
  ['notContains', 'no contiene'],
  ['endsWith', 'termina'],
  ['equals', 'igual'],
  ['notEquals', 'diferente'],
  ['lt', 'menor'],
  ['lte', 'menor igual'],
  ['gt', 'mayor'],
  ['gte','mayor igual'],
])
