trigger:
- main
- dev

variables:
  VM_IMAGE: 'ubuntu-latest'

pool:
  vmImage: $(VM_IMAGE)

stages:
- stage: BuildAndPushAngular
  displayName: 'Build & Push Angular Image'
  jobs:
  - job: AngularJob
    displayName: 'Angular Docker Build and Push'
    steps:
      - task: Docker@2
        displayName: "Build and Push to docker hub"
        inputs:
          containerRegistry: 'dockerhub'
          repository: 'deivycode/services'
          command: 'buildAndPush'
          Dockerfile: '$(Build.Repository.LocalPath)/Dockerfile'
          tags: 'portalfe-sg'
          buildContext: '$(Build.Repository.LocalPath)/'